### ISSUE TITLE
Hidden Services as sdwdate time sources

### ISSUE THREAD

**Issue by HulaHoopWhonix** [Whonix/Whonix#351]
Proposal Status : Approved

Proposal: Use of trusted and reliable HSs as tls date time sources. Solves the clearnet pinning burden and CA SSL MITM. The purpose of this proposal is to avoid automated MITM of "secure" clearnet connections and spoofing of time responses.

The chosen sources are predominantly securedrop instances of major media outlets, making it unlikely that they are hosted on third party servers or on the same server, because of the sensitivity of the documents involved.

I have included this ticket on the git tracker for historical reasons so that development information is publicly accessible.

Also my mail service has been out for the entire day now and I have made headway in making this work.

**Comment by adrelanos** [comment]
> The latest documents Jacob talks about in 31C3 make it a certain fact that any CA backed SSL on the clearnet is MITM'd on the fly by NSA and friends.

I was in that talk, but are you sure he really meant that? Do we have this in textual form somewhere there CA SSL is totally broken?

> The load on Tor argument isn't much considering Facebook a major internet site has a Hidden Service running with no ill effects.

We just took whonix.org hidden service down due to issues:
https://www.whonix.org/forum/index.php/topic,714.0.html

You probably also know this one:
https://blog.torproject.org/blog/hidden-services-need-some-love

Dunno how facebook handles this. How many are using their hs. But facebook can surely spend one or another root server for such experiments using petty cash. They surely got engineers, load balancers, caches and all sorts of cool stuff. Their infrastructure is superb in comparison to others.

Somewhere on trac.torproject.org, if I remember right, Roger said something like "if you are pointing millions of clients to a hidden service for update notification, you might find some interesting scalability issues while not being able to notify about updates anymore". While I think, "millions of clients" was a figure of speech, not actually meaning millions of clients.

Could you please ask (Roger or so) what he thinks about our idea "use (somewhat trustworthy - leak sites) hidden service for extracting time from http headers for time syncing purposes" and how hidden services would scale?

**Comment by HulaHoopWhonix** [comment]
Yes the text source:

http://www.spiegel.de/media/media-35511.pdf (slide 22, 34, 36)

http://www.spiegel.de/international/germany/inside-the-nsa-s-war-on-internet-security-a-1010361.html
You can also infer that from their inability to break Tor SSL while being able to do it to clearnet SSL. The only difference is Tor uses a a hardcoded list of keys in the client while the other relies on the broken CA model. Tor does a lot more than encrypting traffic but I'm just looking that basic point.

***

>pragmatist> To keep things simple I am asking for your permission to allow our timesync mechanism to talk to hidden services on the network. Is the load acceptable?
>Yawning> how many users do you have?
>pragmatist> less than 5 figures
>Yawning> and how often would you make connections to how many hses?
>pragmatist> every few hours and the requests will be made to about a dozen different servers listed on the Freedom of The Press Foundation's securedrop list
>Yawning> I mean, it sounds fine, and another non-sketch HS usecase is always welcome, but I figure I'll ask the important questions

**Comment by adrelanos** [comment]
I don't interpret it that way ("SSL CA's generally or for most part broken"). Also no security news websites or forums interpret it that way. If it were the case, they would be discussing that by now.

The paper says, if they can steal the private key, they can decrypt it. Quite obvious. But when they can steal the private key, they already compromised the machine. I wouldn't wonder if they compromised most data centers were servers are housed nowadays by either legal front door and/or backdoor. In that case however switching to another transport (onion) wouldn't help.

-----

Who is Yawning? Does know as much or enough about hidden services as Roger? With no disrespect, I don't know the person, but statements by random people aren't sufficient.

-----

Don't get me wrong. I'd be eager to implement onion-only. That would be easier than compatibility with both transports (https and onion). But it needs a knowledgeable statement. Creating a compatibility mode and slow transition would take longer and be certainly less fun than just swishing to onion-only.

**Comment by WhonixQubes** [comment]
I haven't looked into all the detail and history of this discussion, but 
just wanted to add one small comment...

CAs are considered GOV infiltrated, by security industry.

So without something like trusted certificate pinning, GOV systems could 
generate a fake SSL cert for each domain Whonix checks, and it would 
probably be trusted and used due to inclusion in local OS/browser root 
CA store.

I see ticket #311 mentions certificate pinning as a future goal.

But on-the-fly GOV generated SSL certs, using something like DPI + 
quantuminsert, with an auto-generated trusted CA signature could 
probably subvert SSL-based sdwdate time syncing right now?

**Comment by HulaHoopWhonix** [comment]
Jacob in 31c3 interprets it that way and when I repeated this interpretation on Tor channel IRC they confirmed it to be so. 

Their operation process is as follows: they either have the private key in their back pocket through CA roots and if they don't they hack into a server and steal it. And as WhonixQubes just said its an open secret for more than a decade that they use legal frontdoors to get their own copy of something like verisign's certifcate keys. Seriously what would stop them from doing so when every other company is being bent over. Do you really believe CA root companies are immune?

***

YawningAngel aka Christopher is a core Tor developer who also works on pluggable transports and very early experiments with post quantum crypto implementations for Tor. I would consider him a good source.

>Don't get me wrong. I'd be eager to implement onion-only. That would be easier than compatibility with both transports (https and onion). But it needs a knowledgeable statement. Creating a compatibility mode and slow transition would take longer and be certainly less fun than just swishing to onion-only.
I agree and thats why I'm advocating for a safe default only.

**Comment by adrelanos** [comment]
@WhonixQubes yes.

**Comment by JasonJAyalaP** [comment]
@adrelanos 
So what's needed to do "only onion, pinned" timeservers?

**Comment by adrelanos** [comment]
Not so technical work:

1) writing a draft, posting to tor-talk if this is a sane idea or will overload hidden services
2) writing a draft, asking the hidden service news sites if they agree to this use case

Started a draft with @HulaHoopWhonix. 

Didn't get confirmation about the "SSL CA traffic almost all broken":
https://lists.torproject.org/pipermail/tor-talk/2015-January/036378.html

Which is bad. Makes writing these drafts harder.

Technical work:

3) Depending on 1, either switch sdwdate's code to use onion-only, either per default or not and either leaving https compatibility mode or not.

**Comment by adrelanos** [comment]
Migrated:
https://phabricator.whonix.org/T131
